name: danielmiranda2.github.io deployment

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo Building the app

  # deploy development
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{vars.TARGET}}
    needs: build
    steps: 
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Github Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "obj/" 
                
  # deploy staging
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{vars.TARGET}}
    needs: deploy-development
    steps: 
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Github Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "obj/"
          
  # deploy production
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{vars.TARGET}}
    needs: deploy-staging
    steps: 
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Github Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "obj/"
